name: furrl_ui
description: A simple UI clone of Furrl and an image maker from collage
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/genre.json

